import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006428",
        "primary-container": "#1b7f3a",
        secondary: "#9c4500",
        "secondary-container": "#ff7a1b",
        "on-primary": "#ffffff",
        "on-primary-container": "#ceffcf",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5e2700",
        background: "#fcf9f8",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0edec",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#3f493e",
        "on-background": "#1c1b1b",
        tertiary: "#555755",
        "tertiary-fixed": "#e2e3e0",
        "tertiary-fixed-dim": "#c6c7c4",
        "tertiary-container": "#6d6f6d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f3f3f0",
        "on-tertiary-fixed": "#1a1c1b",
        "on-tertiary-fixed-variant": "#454745",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#7cdb8a",
        "primary-fixed": "#98f8a4",
        "primary-fixed-dim": "#7cdb8a",
        "secondary-fixed": "#ffdbca",
        "secondary-fixed-dim": "#ffb68e",
        "on-secondary-fixed": "#331200",
        "on-secondary-fixed-variant": "#773300",
        outline: "#6f7a6d",
        "outline-variant": "#becabb",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#006e2d",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      spacing: {
        "container-margin": "16px",
        gutter: "12px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
      },
    },
  },
  plugins: [],
};
export default config;
